In [2]:
import pandas as pd

In [3]:
zomato_df = pd.read_excel('resturant.xlsx')

In [4]:
zomato_df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [5]:
zomato_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  float64
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: float64(1), int64(1), object(15)
memory usage: 6.7+ MB

In [6]:
zomato_df.isna().sum()

url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [7]:
zomato_df.drop(['url','address','phone','menu_item','listed_in(city)'],axis=1,inplace=True)

In [8]:
zomato_df['name'][:50]

0                                                 Jalsa
1                                        Spice Elephant
2                                       San Churro Cafe
3                                 Addhuri Udupi Bhojana
4                                         Grand Village
5                                       Timepass Dinner
6       Rosewood International Hotel - Bar & Restaurant
7                                                Onesta
8                                        Penthouse Cafe
9                                             Smacznego
10    CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...
11                                         Cafe Shuffle
12                                     The Coffee Shack
13                                           Caf-Eleven
14                                      San Churro Cafe
15                                        Cafe Vivacity
16                                         Catch-up-ino
17                                     Kirthi's Biryani
18                                             T3H Cafe
19                        360 Atoms Restaurant And Cafe
20                                     The Vintage Cafe
21                                         Woodee Pizza
22                                      Cafe Coffee Day
23                                         My Tea House
24                                        Hide Out Cafe
25                                            CAFE NOVA
26                                         Coffee Tindi
27                                       Sea Green Cafe
28                                                Cuppa
29                                     Srinathji's Cafe
30                                            Redberrys
31                                           Foodiction
32                                          Sweet Truth
33                                      Ovenstory Pizza
34                                               Faasos
35                                      Behrouz Biryani
36                                       Fast And Fresh
37                                      Szechuan Dragon
38                                    Empire Restaurant
39                         Maruthi Davangere Benne Dosa
40                                            Chaatimes
41                                         Havyaka Mess
42                                           McDonald's
43                                       Domino's Pizza
44                                               Onesta
45                                             Hotboxit
46                                       Kitchen Garden
47                                               Recipe
48                                        Beijing Bites
49                                          Tasty Bytes
Name: name, dtype: object

In [9]:
zomato_df['name'][10]

'CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â\x83Ã\x83Â\x83Ã\x82Â\x82Ã\x83Â\x82Ã\x82Â© Down The Alley'

In [10]:
import re
def clean_names(name):
    if isinstance(name,str):
        result = re.findall(r'[a-zA-z0-9 ]',name)
        res =''.join(result)
        return res

In [11]:
zomato_df['name']=zomato_df['name'].apply(clean_names)

In [12]:
zomato_df['name'][:50]

0                                             Jalsa
1                                    Spice Elephant
2                                   San Churro Cafe
3                             Addhuri Udupi Bhojana
4                                     Grand Village
5                                   Timepass Dinner
6     Rosewood International Hotel  Bar  Restaurant
7                                            Onesta
8                                    Penthouse Cafe
9                                         Smacznego
10                               Caf Down The Alley
11                                     Cafe Shuffle
12                                 The Coffee Shack
13                                        CafEleven
14                                  San Churro Cafe
15                                    Cafe Vivacity
16                                       Catchupino
17                                  Kirthis Biryani
18                                         T3H Cafe
19                    360 Atoms Restaurant And Cafe
20                                 The Vintage Cafe
21                                     Woodee Pizza
22                                  Cafe Coffee Day
23                                     My Tea House
24                                    Hide Out Cafe
25                                        CAFE NOVA
26                                     Coffee Tindi
27                                   Sea Green Cafe
28                                            Cuppa
29                                  Srinathjis Cafe
30                                        Redberrys
31                                       Foodiction
32                                      Sweet Truth
33                                  Ovenstory Pizza
34                                           Faasos
35                                  Behrouz Biryani
36                                   Fast And Fresh
37                                  Szechuan Dragon
38                                Empire Restaurant
39                     Maruthi Davangere Benne Dosa
40                                        Chaatimes
41                                     Havyaka Mess
42                                        McDonalds
43                                    Dominos Pizza
44                                           Onesta
45                                         Hotboxit
46                                   Kitchen Garden
47                                           Recipe
48                                    Beijing Bites
49                                      Tasty Bytes
Name: name, dtype: object

In [13]:
zomato_df['online_order'].unique()

array(['Yes', 'No'], dtype=object)

In [14]:
zomato_df['online_order'].value_counts()/len(zomato_df) #Number of Online Orders

online_order
Yes    0.588665
No     0.411335
Name: count, dtype: float64

In [15]:
zomato_df['book_table'].value_counts()/len(zomato_df)

book_table
No     0.875302
Yes    0.124698
Name: count, dtype: float64

In [16]:
zomato_df['rate'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '3.6/5', '4.6/5', '4.0/5', '4.2/5',
       '3.9/5', '3.1/5', '3.0/5', '3.2/5', '3.3/5', '2.8/5', '4.4/5',
       '4.3/5', 'NEW', '2.9/5', '3.5/5', nan, '2.6/5', '3.8 /5', '3.4/5',
       '4.5/5', '2.5/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5',
       '3.4 /5', '-', '3.6 /5', '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5',
       '4.1 /5', '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5',
       '3.5 /5', '2.7 /5', '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5',
       '4.3 /5', '4.4 /5', '4.9/5', '2.1/5', '2.0/5', '1.8/5', '4.6 /5',
       '4.9 /5', '3.0 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5',
       '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)

In [17]:
float('4.1/5'.split('/')[0])

4.1

In [18]:
import numpy as np

In [19]:
def clean_rate(rate):
    if rate == "NEW" or rate == "-":
        return np.nan
    else:
        cleaned_rate =float(str(rate).split("/")[0])
        return cleaned_rate
zomato_df['rate']=zomato_df['rate'].apply(clean_rate)

In [20]:
zomato_df['rate'].fillna(zomato_df['rate'].mean(),inplace=True)

/tmp/ipython-input-20-3603079835.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  zomato_df['rate'].fillna(zomato_df['rate'].mean(),inplace=True)

In [21]:
# find out top 10 resturants on the basis of voting.
zomato_df.groupby('name')[['votes']].mean().sort_values(by="votes",ascending=False).head(10)

                                    votes
name
Byg Brewski Brewing Company  16588.500000
Toit                         14956.000000
The Black Pearl               9562.333333
Big Pitcher                   9164.500000
Arbor Brewing Company         8396.545455
Prost Brew Pub                7860.900000
Church Street Social          7561.727273
Hoot                          7257.000000
The Hole in the Wall Cafe     7124.875000
Truffles                      7001.372093

In [22]:
# find out top 10 resturants on the basis of rating.

zomato_df.groupby('name')[['rate']].mean().sort_values(by="rate",ascending=False).head(10)

                                    rate
name
Byg Brewski Brewing Company     4.900000
Asia Kitchen By Mainland China  4.900000
Sant Spa Cuisine                4.900000
Punjab Grill                    4.871429
Belgian Waffle Factory          4.844828
Flechazo                        4.800000
OG Variar  Sons                 4.800000
The Pizza Bakery                4.800000
CTR                             4.750000
Barbecue by Punjab Grill        4.750000

In [23]:
# Top 10 costliest Resturants in Banglore

top10_costliest_rest = zomato_df.groupby('name')[['approx_cost(for two people)']].mean().sort_values(by="approx_cost(for two people)",ascending=False).head(10)
top10_costliest_rest

                                       approx_cost(for two people)
name
Le Cirque Signature  The Leela Palace                       6000.0
Royal Afghan  ITC Windsor                                   5000.0
Malties  Radisson Blu                                       4500.0
La Brasserie  Le Meridien                                   4100.0
Jamavar  The Leela Palace                                   4000.0
Riwaz  The RitzCarlton                                      4000.0
Masala Klub  The Taj West End                               4000.0
Alba  JW Marriott Bengaluru                                 4000.0
Dakshin  ITC Windsor                                        4000.0
Dum Pukht Jolly Nabobs  ITC Windsor                         4000.0

In [24]:
# Top 10 cheapest Resturants in Banglore

top10_cheapest_rest = zomato_df.groupby('name')[['approx_cost(for two people)']].mean().sort_values(by="approx_cost(for two people)",ascending=True).head(10)
top10_cheapest_rest

                                 approx_cost(for two people)
name
Srinidhi Sagar Deluxe                              40.000000
Bread  Better                                      50.000000
Funky Food                                         60.000000
Namaste                                            70.000000
Nellore Dosa Camp                                  70.000000
Savera Cafe                                        71.428571
Dosa Cafe                                          80.000000
Dtink Lab                                          80.000000
Shree Ganesh Fruit Juice Centre                    90.000000
Great Indian Rolls                                100.000000

In [25]:
# Resturant Outlets

outlets = zomato_df.groupby('name')[['rate']].count().sort_values('rate',ascending=False).reset_index().rename(columns={'rate':'outletcount'})
outlets

                            name  outletcount
0                Cafe Coffee Day           96
1                         Onesta           85
2                      Just Bake           73
3              Empire Restaurant           71
4              Five Star Chicken           70
...                          ...          ...
8735                1TO3 Kitchen            1
8736          Zayan Kabab Korner            1
8737  Zamorins Mappillah Biryani            1
8738    Zamindars Biryani Durbar            1
8739                Happy Khaana            1

[8740 rows x 2 columns]

In [26]:
# Location with Highest number of resturants

location_with_highest_rest = zomato_df.groupby('location')[['name']].count().sort_values('name',ascending=False).reset_index()
location_with_highest_rest

                 location  name
0                     BTM  5124
1                     HSR  2523
2   Koramangala 5th Block  2504
3                JP Nagar  2235
4              Whitefield  2144
..                    ...   ...
88         West Bangalore     6
89              Yelahanka     6
90                 Jakkur     3
91   Rajarajeshwari Nagar     2
92                 Peenya     1

[93 rows x 2 columns]

In [27]:
# Top categories of Resturants in Banglore

top_categories_rest = zomato_df.groupby('rest_type')[['name']].count().sort_values('name',ascending=False).reset_index()
top_categories_rest
# OR

top_categories_rest1 = zomato_df.groupby('listed_in(type)')[['name']].count().sort_values('name',ascending=False).reset_index()
top_categories_rest1

      listed_in(type)   name
0            Delivery  25937
1            Dine-out  17774
2            Desserts   3593
3               Cafes   1723
4  Drinks & nightlife   1101
5              Buffet    878
6       Pubs and bars    697

In [28]:
# Most Likes Cuisines

most_liked_cuisines = zomato_df.groupby('cuisines')[['votes']].count().sort_values('votes',ascending=False).head(10)
most_liked_cuisines

                                     votes
cuisines
North Indian                          2913
North Indian, Chinese                 2385
South Indian                          1828
Biryani                                918
Bakery, Desserts                       911
Fast Food                              803
Desserts                               766
Cafe                                   756
South Indian, North Indian, Chinese    726
Bakery                                 651

In [29]:
# Number of Resturants respective to Cuisine Type

rest_cuisine_type = zomato_df.groupby('cuisines')[['name']].count().sort_values('name',ascending=False)
rest_cuisine_type

                                             name
cuisines
North Indian                                 2913
North Indian, Chinese                        2374
South Indian                                 1828
Biryani                                       918
Bakery, Desserts                              911
...                                           ...
Italian, Chinese, Continental, North Indian     1
Juices, Beverages, Pizza, Fast Food             1
Italian, North Indian, Continental, BBQ         1
Turkish, Fast Food, Biryani, Chinese            1
Tibetan, Nepalese                               1

[2723 rows x 1 columns]

In [30]:
# Most Expensive Cuisine with respective to Resturant Category

MostCostlyCuisineCategory = zomato_df.groupby(['cuisines','listed_in(type)'])[['approx_cost(for two people)']].mean().sort_values('approx_cost(for two people)',ascending=False)
MostCostlyCuisineCategory

                                                                       approx_cost(for two people)
cuisines                                           listed_in(type)
French, Italian                                    Dine-out                                 6000.0
Continental, Fast Food                             Drinks & nightlife                       4500.0
North Indian, Continental, Japanese, Chinese, S... Dine-out                                 4100.0
                                                   Buffet                                   4100.0
Steak, Mediterranean, Grill                        Dine-out                                 4000.0
...                                                                                            ...
Healthy Food, Beverages, Mexican, Burger, Italian  Dine-out                                    NaN
Mughlai, Chinese, North Indian, South Indian, B... Dine-out                                    NaN
North Eastern                                      Drinks & nightlife                          NaN
South Indian, Chinese, Chettinad                   Delivery                                    NaN
                                                   Dine-out                                    NaN

[5826 rows x 1 columns]

In [31]:
zomato_df['dish_liked']

0        Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
1        Momos, Lunch Buffet, Chocolate Nirvana, Thai G...
2        Churros, Cannelloni, Minestrone Soup, Hot Choc...
3                                              Masala Dosa
4                                      Panipuri, Gol Gappe
                               ...
51712                                                  NaN
51713                                                  NaN
51714                                                  NaN
51715                         Cocktails, Pizza, Buttermilk
51716                                                  NaN
Name: dish_liked, Length: 51717, dtype: object

In [32]:
def splitData(data):
    return [x.strip() for x in str(data).split(',')]

zomato_df['dish_liked'].apply(splitData).explode('dish_liked').value_counts()[:10]

dish_liked
nan           28078
Pasta          3409
Burgers        3024
Cocktails      2832
Pizza          2737
Biryani        2092
Coffee         1994
Mocktails      1887
Sandwiches     1676
Paratha        1566
Name: count, dtype: int64

In [33]:
# Top 10 dine out resturants

dine_out_rest = zomato_df[zomato_df['listed_in(type)'] == 'Dine-out'] \
    .groupby('name')[['rate']] \
    .mean() \
    .sort_values('rate', ascending=False)
dine_out_rest

                                     rate
name
Asia Kitchen By Mainland China   4.900000
Byg Brewski Brewing Company      4.900000
Sant Spa Cuisine                 4.900000
Punjab Grill                     4.866667
Flechazo                         4.833333
...                                   ...
Mamma Mexicana                   2.200000
Bageecha                         2.150000
Deckers Lane                     2.100000
Fusion Lounge                    2.000000
Alibi  Maya International Hotel  1.800000

[6351 rows x 1 columns]

In [34]:
# Top 10 resturants for Desserts

dessert_rest = zomato_df[zomato_df['listed_in(type)'] == 'Desserts'].groupby('name')[['rate']].count().sort_values('rate', ascending=False).head(10)
dessert_rest

                        rate
name
Just Bake                 31
Baskin Robbins            30
Sweet Truth               29
Kanti Sweets              29
Keventers                 26
Corner House Ice Cream    26
Sweet Chariot             25
The French Loaf           23
Natural Ice Cream         23
Me And My Cake            22

In [35]:
# Dish Liked with respect to Lacation

DishLiked = zomato_df.groupby(['location','dish_liked'])[['name']].count().reset_index().sort_values('name', ascending=False)
DishLiked

,location,dish_liked,name
1123,Cunningham Road,"Cappuccino, Eclair, Pizza, Coffee, Blueberry C...",25
10,BTM,Biryani,24
3731,Langford Town,"Cocktails, Pizza, French Fries",22
3171,Koramangala 4th Block,"Biryani, Breakfast Buffet, Fish, Salads, Burge...",21
3290,Koramangala 5th Block,"Burgers, Pasta, Chocolate Mousse, Potato Wedge...",21
...,...,...,...
321,Banashankari,"Salads, Panneer Butter Masala, Rabri, Gajar Ka...",0
2609,Jayanagar,"Palak Paneer, Aam Panna, Crispy Corn, Gajar Ka...",0
2630,Jayanagar,"Pasta, Tomato Soup, Salad, Kulcha, Chaat, Kulf...",0
3965,Malleshwaram,"Jal-jeera, Roti, Dhokla, Biryani, Kheer, Chaac...",0
4589,Rajajinagar,"Manchurian, Vegetarian, Sweet Corn Soup, Panee...",0

In [36]:
dish_liked1 = zomato_df['dish_liked'].apply(splitData).explode('dish_liked1').value_counts()
biryani = pd.Series((x for x in dish_liked1.index if 'biryani' in x.lower()))
dish_liked1

dish_liked
nan                     28078
Pasta                    3409
Burgers                  3024
Cocktails                2832
Pizza                    2737
                        ...
Prawn Rolls                 1
Tandoori Fries              1
Saha Chowmein               1
Chicken Teriyaki Sub        1
Fried Momo                  1
Name: count, Length: 2793, dtype: int64